archive/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from . import views

app_name='archive'
urlpatterns = [
    path('', TemplateView.as_view(template_name='archive/main_menu.html'), name='main'),

    #path('oilpainting/', TemplateView.as_view(template_name='archive/main_menu.html'), name='oilpainting'),

    path('oilpainting/', views.PicListView.as_view(), name='oilpainting'),
    path('oilpainting/pic/<int:pk>', views.PicDetailView.as_view(), name='pic_detail'),
    path('oilpainting/pic/create',
         views.PicCreateView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_create'),
    path('oilpainting/pic/<int:pk>/update',
         views.PicUpdateView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_update'),
    path('oilpainting/pic/<int:pk>/delete',
         views.PicDeleteView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_delete'),

    path('oilpainting/pic_picture/<int:pk>', views.stream_file, name='pic_picture'), #actual url to serve the image
    #url generating the html and picture




    path('bookart/', TemplateView.as_view(template_name='archive/main_menu.html'), name='bookart'),
    path('landscapepainting/', TemplateView.as_view(template_name='archive/main_menu.html'), name='landscapepainting'),
    path('watercolor/', TemplateView.as_view(template_name='archive/main_menu.html'), name='watercolor'),
    path('figuredrawing/', TemplateView.as_view(template_name='archive/main_menu.html'), name='figuredrawing'),
]

blog/urls.py
from django.urls import path, reverse_lazy
from .views import (
                    BlogListView,
                    BlogDetailView,
                    BlogCreateView,
                    BlogUpdateView,
                    BlogDeleteView,

                    ReviewCreateView,
                    ReviewDeleteView,
                    )


app_name='blog'
urlpatterns=[
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'), # new
    path('post/new/', BlogCreateView.as_view(), name='post_new'), # new
    path("post/",BlogListView.as_view(),name="main"),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'), # new



    path('post/<int:pk>/review', 
        ReviewCreateView.as_view(), name='post_review_create'),
    path('review/<int:pk>/delete',
        ReviewDeleteView.as_view(success_url=reverse_lazy('blog:post_detai')), name='post_review_delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView


urlpatterns = [
    #Django admin
    path('admin/', admin.site.urls),

    #User Management && #user authentication
    path("accounts/", include("allauth.urls")), 

    #Local apps
    path("accounts/", include("accounts.urls")), # accounts app

    path("blog/", include("blog.urls")),
    path("menu/",include("menu.urls")),
    path("archive/",include("archive.urls")),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
   
]+ static(settings.STATIC_URL,
 document_root=settings.STATIC_ROOT)

archive/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


class Pic(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Picture
    picture = models.BinaryField(null=True, blank=True, editable=True)  #pixel goes here
    content_type = models.CharField(max_length=256, null=True, blank=True,  #content_type==metedata in network
                                    help_text='The MIMEType of the file')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

archive/forms.py
from django import forms
from archive.models import Pic
from django.core.files.uploadedfile import InMemoryUploadedFile
from archive.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):    #"ModelForm" get data from the model
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)   #upload field
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Pic                         #"Pic" is inhereted throgh ModelForm
        fields = ['title', 'text', 'picture']  # Picture is manual because picture comes from upload_field_name

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()          #pulling data from the browser
        pic = cleaned_data.get('picture')       #grabbing the picture from the form
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy , grab the picture from the form
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()                              #read all of the pixels in the file
            instance.content_type = f.content_type                      #image/png
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

archive/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.files.uploadedfile import InMemoryUploadedFile

from archive.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

from archive.models import Pic
from archive.forms import CreateForm


class PicListView(OwnerListView):
    model = Pic
    template_name = "archive/list.html"


class PicDetailView(OwnerDetailView):
    model = Pic
    template_name = "archive/detail.html"


class PicCreateView(LoginRequiredMixin, View):                      #views.py works as a controller,
    template_name = 'archive/form.html'                                   # talking to the browser, through forms
    success_url = reverse_lazy('archive:oilpainting')                             # interacting with the database, through models

    def get(self, request, pk=None): #get the form first, building the form includimg ['title', 'text', 'picture'] fields
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):                               #working with the form
        form = CreateForm(request.POST, request.FILES or None)            #constructing the form first

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving                       #working with the model
        pic = form.save(commit=False)                                   #get me the model, but don't store in the database
        pic.owner = self.request.user
        pic.save()
        return redirect(self.success_url)


class PicUpdateView(LoginRequiredMixin, View):
    template_name = 'archive/form.html'
    success_url = reverse_lazy('archive:oilpainting')

    def get(self, request, pk):
        pic = get_object_or_404(Pic, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Pic, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        return redirect(self.success_url)


class PicDeleteView(OwnerDeleteView):
    model = Pic
    template_name = "archive/delete.html"


def stream_file(request, pk):
    pic = get_object_or_404(Pic, id=pk)
    response = HttpResponse()          #html respose
    response['Content-Type'] = pic.content_type #not text, but image/png shown in HEADER
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)     #write the pixels
    return response

archive/templates/archive/archive_base.html
{% extends 'base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}

{% block content %}
<div class="container" style="font-family: 'Bodoni Moda';"">

<h2 class="text-center">Archive</h2>
<hr>

<nav class="navbar  navbar-dark mx-auto"" style="font-size:1.8em;font-family: 'Bodoni Moda', serif;">

  <div class="mx-auto" style="width:80%;margin:auto">
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav" >

      <!-- Assign output of url function to a variable named
          'xyz' to use in the if statement -->
      {% url 'archive:oilpainting' as xyz %}
      <li {% if request.get_full_path == xyz %}class="active"{% endif %}>
          <a href="{% url 'archive:oilpainting' %}">oil painting</a></li>

      {% url 'archive:bookart' as abc1 %}
      <li {% if request.get_full_path == abc1 %}class="active"{% endif %}>
          <a href="{% url 'archive:bookart' %}">book art</a></li>

      {% url 'archive:landscapepainting' as abc2 %}
      <li {% if request.get_full_path == abc2 %}class="active"{% endif %}>
          <a href="{% url 'archive:landscapepainting' %}">landscape painting</a></li>

      {% url 'archive:watercolor' as abc3 %}
      <li {% if request.get_full_path == abc3 %}class="active"{% endif %}>
          <a href="{% url 'archive:watercolor' %}">Watercolor</a></li>

      {% url 'archive:figuredrawing' as abc4 %}
      <li {% if request.get_full_path == abc4 %}class="active"{% endif %}>
          <a href="{% url 'archive:figuredrawing' %}">Figure Drawing</a></li>


    </ul>

  </div>
</nav>


</div>

{% block subcontent %}
{% endblock %}

{% endblock %}

archive/templates/archive/delete.html
{% extends 'archive/archive_base.html' %}
{% block content %}
<h1>Delete Pic</h1>

<p>Are you sure you want to delete the pic: {{ pic }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

archive/templates/archive/detail.html
{% extends 'archive/archive_base.html' %}
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
</svg>
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}

{% block subcontent %}
<div class="container" style="font-family: 'Bodoni Moda'; text-align:center ; margin-bottom:15em;">
  <h3 style="float: right;" >
    <a href="{% url 'archive:oilpainting' %}">go back</a>
  </h3>
{% if pic.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:50%;margin-top: 50px; border:3px solid black;" src="{% url 'archive:pic_picture' pic.id %}">
<!-- display the picture-->


<span style="float: center;">

<h3>{{ pic.title }}</h3>
({{ pic.updated_at|naturaltime }})
<p>{{ pic.text }}</p>


{% if pic.owner == user %}
<a href="{% url 'archive:pic_update' pic.id %}"><i class="fa fa-pencil"></i>update |</a>
<a href="{% url 'archive:pic_delete' pic.id %}"><i class="fa fa-trash"></i>delete</a>
{% endif %}
</span>

{% endif %}
</div>


</div>
{% endblock %}

archive/templates/archive/form.html
{% extends 'archive/archive_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<p>
  <!--enctype is essential in submitting files -->
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'archive:oilpainting' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<!--whenever we hit the submit button, jQuery will check the size of the uploaded file -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
</div>
{% endblock %}

archive/templates/archive/list.html
{% extends 'archive/archive_base.html' %}

{% block subcontent %}

<div class="container" style="font-family: 'Bodoni Moda';">
<h1 style="text-align:center;">Oil Painting<span style="text-align:end;"><h4>

  {% if user.is_authenticated %}
  <a href="{% url 'archive:pic_create' %}"> Add an Pic</a>
  {% endif %}
</h4></span></h1>




{% if pic_list %}

<div class="container mt-4 mb-4 ml-4 row" style="margin-right:auto; margin-left:auto;padding:10%;">

  {% for pic in pic_list %}

    <div class="card
      text-center col-lg-3 col-md-4 col-sm-6 col-xs-12 "
      style="height: 30%;background-color:#f6f0e6; border: solid 10px #f6f0e6; border-radius:15px; border:solid white 10px; float:center;" >
        <img src= "{% url 'archive:pic_picture' pic.id %}" class="card-img-top rounded"alt="" style="height: 13rem; margin-top:1em;">
        <div class="card-body">
          <ul  style="list-style-type: none;margin: 0;padding: 0;"">
            <li>
              <p>
                <a href="{% url 'archive:pic_detail'  pic.id %}">{{ pic.title }}</a>
                <br>
                {% if pic.owner == user %}
                (<a href="{% url 'archive:pic_update' pic.id %}">Edit</a> |
                <a href="{% url 'archive:pic_delete' pic.id %}">Delete</a>)
                {% endif %}
              </p>
            </li>
          </ul>
        </div>
      <br>

      </div>
  {% endfor %}

  </div>

{% else %}
  <p>There are no pics in the database.</p>
{% endif %}
</p>


{% endblock %}
</div>

archive/templates/archive/main_menu.html
{% extends 'archive/archive_base.html' %}