accounts/urls.py
from django.urls import path
from .views import SignUpView 
from django.views.generic import TemplateView

app_name="accounts"
urlpatterns=[
    #path("signup/", SignUpView.as_view(), name="signup"),
    path('myprofile/', TemplateView.as_view(template_name='myprofile.html'), name='myprofile'),
    #path("profile/",ProfileView.as_view(),name="profile" )
]

#SignUpView is based on built-in UserCreationForm  on projectLevel && generic.Createview Class on app's level

archive/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from . import views

app_name='archive'
urlpatterns = [
    path('', TemplateView.as_view(template_name='archive/main_menu.html'), name='main'),

    #path('oilpainting/', TemplateView.as_view(template_name='archive/main_menu.html'), name='oilpainting'),

    path('oilpainting/', views.PicListView.as_view(), name='oilpainting'),
    path('oilpainting/pic/<int:pk>', views.PicDetailView.as_view(), name='pic_detail'),
    path('oilpainting/pic/create',
         views.PicCreateView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_create'),
    path('oilpainting/pic/<int:pk>/update',
         views.PicUpdateView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_update'),
    path('oilpainting/pic/<int:pk>/delete',
         views.PicDeleteView.as_view(success_url=reverse_lazy('archive:oilpainting')), name='pic_delete'),

    path('oilpainting/pic_picture/<int:pk>', views.stream_file, name='pic_picture'), #actual url to serve the image
    #url generating the html and picture




    path('bookart/', TemplateView.as_view(template_name='archive/main_menu.html'), name='bookart'),
    path('landscapepainting/', TemplateView.as_view(template_name='archive/main_menu.html'), name='landscapepainting'),
    path('watercolor/', TemplateView.as_view(template_name='archive/main_menu.html'), name='watercolor'),
    path('figuredrawing/', TemplateView.as_view(template_name='archive/main_menu.html'), name='figuredrawing'),
]

blog/urls.py
from django.urls import path, reverse_lazy
from .views import (
                    BlogListView,
                    BlogDetailView,
                    BlogCreateView,
                    BlogUpdateView,
                    BlogDeleteView,

                    ReviewCreateView,
                    ReviewDeleteView,
                    )


app_name='blog'
urlpatterns=[
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'), # new
    path('post/new/', BlogCreateView.as_view(), name='post_new'), # new
    path("post/",BlogListView.as_view(),name="main"),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'), # new



    path('post/<int:pk>/review', 
        ReviewCreateView.as_view(), name='post_review_create'),
    path('review/<int:pk>/delete',
        ReviewDeleteView.as_view(success_url=reverse_lazy('blog:post_detai')), name='post_review_delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView


urlpatterns = [
    #Django admin
    path('admin/', admin.site.urls),

    #User Management && #user authentication
    path("accounts/", include("allauth.urls")), 

    #Local apps
    path("accounts/", include("accounts.urls")), # accounts app

    path("blog/", include("blog.urls")),
    path("menu/",include("menu.urls")),
    path("archive/",include("archive.urls")),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
   
]+ static(settings.STATIC_URL,
 document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name='menu'
urlpatterns = [
    path('', TemplateView.as_view(template_name='menu/main_menu.html'), name='main'),
    path('page1', TemplateView.as_view(template_name='menu/main_menu.html'), name='page1'),
    path('page2', TemplateView.as_view(template_name='menu/main_menu.html'), name='page2'),
    path('page3', TemplateView.as_view(template_name='menu/main_menu.html'), name='page3'),
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!--other templates will inherite by adding at here  -->
<html>
  <head>
    <title>GreenField</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

    <link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

   
    
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

    <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz@6..96&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>
  <body>
    {% block navbar %} {% endblock %}


      {% block content %}

      {% endblock content %}
    

      
  </body>
<footer>{% block footer %} {% endblock %}</footer>

</html>

templates/base_menu.html
{% extends 'base.html' %}
{% load static %}
 <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
<nav class="navbar  navbar-dark navbar-default" style="color:pink;font-family: 'Bodoni Moda', serif;">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'home' %}">Greenfield</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">

      <!-- Assign output of url function to a variable named
          'xyz' to use in the if statement -->
      {% url 'menu:main' as xyz %}
      <li {% if request.get_full_path == xyz %}class="active"{% endif %}>
          <a href="{% url 'archive:main' %}">Archive</a></li>

      {% url 'menu:page1' as abc1 %}
      <li {% if request.get_full_path == abc1 %}class="active"{% endif %}>
          <a href="{% url 'blog:main' %}">Exhibition</a></li>

      {% url 'menu:page2' as abc2 %}
      <li {% if request.get_full_path == abc2 %}class="active"{% endif %}>
          <a href="{% url 'menu:page2' %}">Artists</a></li>

      <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">Event
          <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'menu:page3' %}">en plain air</a><
        </ul>
       </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
      <!-- gravatar depends on app_tags being loaded -->
      <!-- https://brobin.me/blog/2016/07/super-simple-django-gravatar/ -->
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        {{user.username}}<span class="caret"></span></a>


        <ul class="dropdown-menu">
            <li><a href="{% url 'account_logout' %}?next={% url 'home' %}">Logout</a></li>
            <li><a href="{% url 'accounts:myprofile' %}">My Profile</a></li>
        </ul>
       </li>
       {% else %}
       <li><a href="{% url 'account_login' %}?next={% url 'home' %}">Login</a></li>
       <li><a href="{% url 'account_signup' %}?next={% url 'home' %}">Signup</a></li>

       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

templates/home.html
<!-- templates/home.html -->
{% extends 'base_menu.html' %}
{% load static %}


{% block content %}
<div style="font-family: 'Bodoni Moda', sans-serif; width:100%;">
<div class="container" style="position: relative;width:100%" >

  <img  src="{%static "images/sea.jpg"%}"   width="100%">

<h5 style="position: absolute;
top: 50;
width: 100%;
text-align: center;
font-size: 3.5em; font-family: 'Bodoni Moda', sans-serif;color: #5D6D7E;"
>The World is waiting <br>for a Talented Artist</h5> 


</div>
<br><br><br>

<!--Greenfield's Mission Description -->

  <div class="container">
    <p style="
      width: 100%;
      text-align: center;
      font-size: 2.3em; 
      font-family: 'Bodoni Moda', sans-serif;
      color: #5D6D7E;letter-spacing: 1px;">
      Greenfield's Mission<br><br>
      <span style="font-size:0.6em;line-height:1.6;"> 
        We are creating a digital space
      <br>for green field art lovers to <br>showcase artworks and draw<br>  inspiration from the community. </span></p>
  </div>
  <br><br><br>



<!--card items-->

<div class="container-fluid mt-4 mb-4  row" style="margin-right:auto; margin-left:auto;padding:5%;text-align: center;">
<p style="
width: 100%;
text-align: center;
font-size: 3em; 
font-family: 'Bodoni Moda', sans-serif;
color: #5D6D7E;letter-spacing: 1px;">

  <div class=" card text-center col-md-4 col-sm-6 col-xs-12" style="width: 30%; height: 25rem;border-radius:15px; border:solid #EAEDED 10px; float:center; margin-right:4px; ">
    <img  src="{%static "images/archive.png"%}"   class="card-img-top rounded"alt="" style="height: 13rem; margin-top:1em;" >
    <br>
    <div class="card-body">
       <a href="{% url 'archive:main' %}" style="background-color:#9CC3C2;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        border-radius: 4px;
        font-size: 25px;
       ">Archive</a>
    </div>
  </div>

  <div class=" card text-center col-md-4 col-sm-6 col-xs-12"" style="width: 30%;height: 25rem;border-radius:15px; border:solid #EAEDED 10px; float:center;  margin-right:4px;" >
    <img  src="{%static "images/workshop.png"%}"   class="card-img-top rounded"alt="" style="height: 13rem; margin-top:1em;">
    <div class="card-body">
       <a href="#" style="background-color:#98ABC2;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        border-radius: 4px;
        font-size: 25px;
       ">Workshop</a>
    </div>
  </div>

  <div class=" card text-center col-md-4 col-sm-6 col-xs-12"" style="width: 30%;height: 25rem;border-radius:15px; border:solid #EAEDED 10px; float:center;  margin-right:4px;">
    <img  src="{%static "images/event.png"%}"   class="card-img-top rounded"alt="" style="height: 15rem; margin-top:1em;">
    <div class="card-body">
       <a href="#" style="background-color:#BD95C1;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        border-radius: 4px;
        font-size: 25px;
       ">Event</a>
    </div>
  </div>
  

  
 
</p>
</div>

</div>
{% endblock content %}


<!--footer-->
{% block footer %}
<div class="container" style="width:100% ;height:30rem; background-color:#EAEDED;margin-top: 5em;">


</div>

{% endblock %}

templates/myprofile.html
{% extends 'base_menu.html' %}


{% block content %}

{% if user.is_authenticated %}

hi{{user.email}}

{% endif %}
{% endblock %}

templates/post_delete.html
<!-- templates/post_delete.html -->
{% extends 'base_menu.html' %}
{% block content %}
<h1>Delete post</h1>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm">
  </form>
{% endblock content %}

templates/post_detail.html
<!-- templates/post_detail.html -->
{% extends 'base_menu.html' %}

{% block content %}
<div class="container">
  <div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
  </div>


  {% if user.is_authenticated %}
  <br clear="all"/>
  <p>
  {% load crispy_forms_tags %}
  <form method="post" action="{% url 'blog:post_review_create' post.id %}">
      {% csrf_token %}
      {{ form.as_p }}
  <input type="submit" value="Submit">
  <input type="submit" value="All Posts" onclick="window.location.href='{% url 'blog:main' %}';return false;">
  </form>
  </p>
  
    


  {% endif %}


  <div>
    <h3>Reviews</h3> <ul>
    {% for review in post.reviews.all %}
    <li>{{ review.review }} ({{ review.author }})</li> 
    
    {% if user == comment.owner %}
    <a href="{% url 'blog:post_review_delete' review.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}


    {% endfor %}
    </ul>
  </div>



  






  
  <a href="{% url 'blog:post_edit' post.pk %}">+ Edit Blog Post</a>
  <p><a href="{% url 'blog:post_delete' post.pk %}">+ Delete Blog Post</a></p>
</div>
  {% endblock content %}

templates/post_edit.html
<!-- templates/post_edit.html -->
{% extends 'base_menu.html' %}
{% block content %}
  <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Update">
    </form>
    {% endblock content %}

templates/post_list.html
<!-- templates/home.html -->
{% extends 'base_menu.html' %}



{% block content %}
<div class="container" style>




  {% for post in object_list %}
    <div class="post-entry">
      <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
      <p>{{ post.body }}</p>
    </div>
  {% endfor %}



</div>
{% endblock content %}

templates/post_new.html
<!-- templates/post_new.html -->
{% extends 'base_menu.html' %}
{% block content %}
  <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save">
    </form>
{% endblock content %}

templates/post_review_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Review</h1>

<p>Are you sure you want to delete</p>
<p>{{ review.review }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'blog:post_detail' review.post.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}